<template>
  <div class="loadingio-spinner-dual-ring-ut6b2y6tqm" v-bind:class="classObject">
    <div class="ldio-9b9quhg9k6r">
      <div></div>
      <div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Loading',
  data() {
    return {
      classObject: {
        play: false,
        pause: false,
      },
    };
  },
  methods: {
    onPlay() {
      this.classObject.play = true;
      this.classObject.pause = false;
    },
    onPause() {
      this.classObject.pause = true;
      this.classObject.play = true;
    },
  },
};
</script>

<style scoped>
@keyframes ldio-9b9quhg9k6r {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-9b9quhg9k6r div {
  box-sizing: border-box !important;
}
.ldio-9b9quhg9k6r > div {
  position: absolute;
  width: 78px;
  height: 78px;
  top: 11px;
  left: 11px;
  border-radius: 50%;
  border: 8px solid #000;
  border-color: #fe718d transparent #fe718d transparent;
}

.play {
  animation: ldio-9b9quhg9k6r 1s linear infinite;
}

.pause {
  animation-play-state: paused;
}

.ldio-9b9quhg9k6r > div:nth-child(2) {
  border-color: transparent;
}
.ldio-9b9quhg9k6r > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-9b9quhg9k6r > div:nth-child(2) div:before,
.ldio-9b9quhg9k6r > div:nth-child(2) div:after {
  content: '';
  display: block;
  position: absolute;
  width: 8px;
  height: 8px;
  top: -8px;
  left: 27px;
  background: #fe718d;
  border-radius: 50%;
  box-shadow: 0 70px 0 0 #fe718d;
}
.ldio-9b9quhg9k6r > div:nth-child(2) div:after {
  left: -8px;
  top: 27px;
  box-shadow: 70px 0 0 0 #fe718d;
}
.loadingio-spinner-dual-ring-ut6b2y6tqm {
  width: 40px;
  height: 40px;
  display: inline-block;
  overflow: hidden;
  background-color: transparent;
}
.ldio-9b9quhg9k6r {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.4);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-9b9quhg9k6r div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>